Loading a model (extracted)

In [2]:
import pickle

In [3]:
with open("salary_predictor","rb") as file:
    lin = pickle.load(file)

In [4]:
lin.predict([[7]])

array([91941.93644885])

In [5]:
import joblib

In [6]:
lin2 = joblib.load("salary_predictor_2")

In [7]:
lin2.predict([[7]])

array([91941.93644885])

In [8]:
lin.intercept_

np.float64(25792.20019866871)

In [9]:
lin.coef_

array([9449.96232146])